### ISSUE TITLE
Se deben solucionar algunos problemas con las alertas y las comprobaciones

### ISSUE THREAD

**Issue by kholostyak17** [Jorge-GD/4geek-Basico-FormularioBoostrap-Javascript#1]
A continuación detallo los errores que se deben solucionar:
- El CVC se muestra como inválido a pesar de que es correcto, y solo desaparece la alerta cuando se introducen más de 5 dígitos
https://github.com/Jorge-GD/4geek-Basico-FormularioBoostrap-Javascript/blob/e818593b0fbf45ef9917d264a5061fe12d86abe8/src/app.js#L75
![image](https://user-images.githubusercontent.com/80543950/127449731-98257d2a-425f-472e-8b27-856ba29994c8.png)

- Tanto en el nombre, como los apellidos y la ciudad, se deberían tener también en cuenta el uso de espacios, _(aconsejable también, pero no necesario en este ejercicio: puntos, comas, acentos, y letras "Ñ")_ a la hora de comprobar si es un string.
https://github.com/Jorge-GD/4geek-Basico-FormularioBoostrap-Javascript/blob/e818593b0fbf45ef9917d264a5061fe12d86abe8/src/app.js#L218

- El cuadro de seleccionar país siempre mantiene una alerta encima a pesar de estar completo.
_- Al cuadro para seleccionar país se le podría poner un diseño más parecido al resto de entradas_

- Bueno, y tener en cuenta que el mensaje no es un `<input>` sino un `<textarea>` y este no necesita de validación

![image](https://user-images.githubusercontent.com/80543950/127448985-f30c79e8-bb7a-4f99-a667-8b14b96d8ba2.png)

**Comment by Jorge-GD** [comment]
Ya esta solucionado lo que me dices.

> El CVC, comprueba que sean solo 4 dígitos y que sean números
> Comprueba si hay espacios y también da por buenos nombres con ñ y acentos.
> Cuadro de ciudad ya deja de mostrar error cuando tiene algo añadido.
>Cambiado la obligatoriedad de poner revisar el textarea.
